version: '3.8'
services:
  vite_docker:
    container_name: pwa_frontend
    image: node:alpine
    working_dir: /srv/app
    entrypoint: /bin/sh
    command: ["-c", "npm install && npm run build && npm run start"]
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true