version: '3.8'
services:
  pwa_frontend:
    container_name: pwa_frontend
    image: node:alpine
    working_dir: /srv/app
    entrypoint: /bin/sh
    command: ["-c", "npm install && npm run build && npm run start"]
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true

  pwa_backend:
    container_name: pwa_backend
    image: 'node:latest'
    working_dir: /home/node/app
    command:
        - /bin/sh
        - '-c'
        - 'npm install && npm start'
    ports:
        - '3000:3000'
    volumes:
        - './backend/src:/home/node/app'